SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, (MAXS-SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA b1 INNER JOIN (SELECT YEAR(DIFFERENTIATION_DATE) as year, MAX(SIZE_OF_COLONY) AS MAXS
                               FROM ECOLI_DATA
                               GROUP BY YEAR(DIFFERENTIATION_DATE)) b1 ON YEAR(DIFFERENTIATION_DATE) = year
ORDER BY YEAR, YEAR_DEV;
                    