SELECT CATEGORY, sum(sales) AS TOTAL_SALES
FROM BOOK INNER JOIN BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') like '2022-01'
GROUP BY CATEGORY
ORDER BY CATEGORY;